industry_location_examples = [
    {"industry": "PE Resins", "location": "US"},
    {"industry": "Film Distribution", "location": "Midwest" },
    {"industry": "Film Entertainment: Film Distribution", "location": "Midwest" },
    {"industry": "Packaging Boxes", "location": "IN" },
    {"industry": "Packaging: Packaging Boxes", "location": "IN" },
    {"industry": "Packaging: Packaging Boxes", "location": "india" },
    {"industry": "Road Freight", "location": "Europe"},
    {"industry": "MRO", "location": "South America"},
    {"industry": "Film (BOPP Film, BOPET, PE Film etc)", "location": "CN" },
    {"industry": "Flexible Packaging: Film (BOPP Film, BOPET, PE Film etc)", "location": "CN" },
    {"industry": "Distribution Services (Distribution, Mastering, Localization etc)", "location": "Northern America"},
    {"industry": "Film Entertainment: Distribution Services (Distribution, Mastering, Localization etc)", "location": "Northern America"},
    {"industry": "ALUMINIUM", "location": "Northern America" },
    {"industry": "BOARD", "location": "Eastern Asia" },
    {"industry": "CONSTRUCTION", "location": "Central Asia" },
    {"industry": "ENERGY & UTILITY", "location": "South-eastern Asia" },
    {"industry": "EQUIPMENT & MACHINERY", "location": "Southern Asia" },
    {"industry": "EXTERNAL MANUFACTURING / TOLLING", "location": "Northern America" },
    {"industry": "FACILITIES MANAGEMENT", "location": "New England" },
    {"industry": "HR SERVICES", "location": "Mid Atlantic" },
    {"industry": "IT & TELECOM", "location": "Northern Africa" },
    {"industry": "LIQUIDS", "location": "Southern Africa" },
    {"industry": "LOGISTICS", "location": "Western Africa" },
    {"industry": "MRO", "location": "Eastern Africa" },
    {"industry": "PACKAGING", "location": "Oceania" },
    {"industry": "PAPER", "location": "Northern Europe" },
    {"industry": "PROFESSIONAL SERVICES", "location": "Southern Europe" },
    {"industry": "RESINS", "location": "Western Europe" },
]

company_name_examples = [
    "ExxonMobil",
    "Borouge",
    "Sigma Chemtrade",
    "HPCL Mittal Energy",
    "L M Goes Embalagens",
    "Westrock",
    "International Paper",
    "Dine Cartonnages",
    "Jiangin Yonghe Packaging Products",
    "Fritz Foss",
    "Husky Technologies",
    "KRC Custom Manufacturing",
    "Braroll Acessorios Industriais",
    "Jindal Films",
    "Klöckner Pentaplast",
    "Klockner Pentaplast",
    "Entertainment Partners",
    "Universal McCann",
    "Little Island Productions",
    "Commerzbank AG",
    "Linklaters",
    "CBS News",
    "Deloitte",
    "Bloomberg",
]
