industry_location_examples = [
    {"industry": "PE Resins", "industry_context": "Elastomer, HDPE Bio, LDPE C4", "location": "US"},
    {"industry": "Film Distribution", "industry_context": "Movies", "location": "Midwest" },
    {"industry": "Packaging Boxes", "industry_context": "Carton Boxes, Metal Boxes, Plastic Boxes", "location": "IN" },
    {"industry": "Road Freight", "industry_context": "Flatbed Truckload, Less than Truckload (LTL), Tanker Truckings", "location": "Europe"},
    {"industry": "Film", "industry_context": "BOPP Film, BOPET, PE Film", "location": "CN" },
    {"industry": "Flexible Packaging", "industry_context": "BOPP Film, BOPET, PE Film", "location": "CN" },
    {"industry": "Distribution Services", "industry_context": "Distribution, Mastering, Localization", "location": "Northern America"},
    {"industry": "Film Entertainment: Distribution Services", "industry_context": "Distribution, Mastering, Localization", "location": "Northern America"},
    {"industry": "Converter Foil", "industry_context": "Aluminium", "location": "Northern America" },
    {"industry": "BOARD", "industry_context": "Chemi Thermo Mechanical Pulp Board, Folding Box Board, Formable Board", "location": "Eastern Asia" },
    {"industry": "CONSTRUCTION", "industry_context": "BUILDING CONSTRUCTION, ELECTRICAL INSTALLATION, HVAC INSTALLATION", "location": "Europe" },
    {"industry": "OIL/ FUEL", "industry_context": "BIO FUEL, DIESEL, GASOLINE OR PETROL", "location": "South-eastern Asia" },
    {"industry": "CONVERTING AND FINISHING MACHINES", "industry_context": "BLENDER EQUIPMENT, CNC MACHINING CENTERS, CONVERTING LINES/MACHINES", "location": "Southern Asia" },
    {"industry": "EXTERNAL MANUFACTURING / TOLLING", "industry_context": "ASSEMBLY SERVICES, METALIZATION SERVICES, POUCHING/BAGGING SERVICES", "location": "Northern America" },
    {"industry": "CLEANING SUPPLIES", "industry_context": "CLEANING EQUIPMENT, SOAPS AND SANITIZERS CLEANING SUPPLIES, TOILET PAPER", "location": "New England" },
    {"industry": "HR SERVICES", "industry_context": "CORPORATE SOCIAL RESPONSIBILITY (CSR), EMPLOYEE HEALTH INSURANCE, FLEET MANAGEMENT", "location": "Mid Atlantic" },
    {"industry": "IT & TELECOM", "industry_context": "IT HARDWARE, IT NETWORK & TELECOM, IT SERVICES, IT SOFTWARE", "location": "Northern Africa" },
    {"industry": "LIQUIDS", "industry_context": "Adhesives, Inks, Solvents", "location": "Southern Africa" },
    {"industry": "LOGISTICS", "industry_context": "AIR FREIGHT, DELIVERY FLEET, OCEAN FREIGHT", "location": "Western Africa" },
    {"industry": "LABORATORY", "industry_context": "LAB EQUIPMENT MAINTENANCE AND REPAIR, POLYMER CHARACTERIZATION, THERMAL ANALYSIS", "location": "Africa" },
    {"industry": "PACKAGING", "industry_context": "BAGS, BOXES, CORRUGATED", "location": "Oceania" },
    {"industry": "PAPER", "industry_context": "", "location": "Northern Europe" },
    {"industry": "PROFESSIONAL SERVICES", "industry_context": "CONSULTING, FINANCIAL SERVICES, LEGAL SERVICES", "location": "LATAM" },
    {"industry": "Cocoa, Nuts & Seeds", "industry_context": "Food Ingredients", "location": "Asia Pacific"},
    {"industry": "Cheese, Cultures, Milk Powders", "industry_context": "Food Ingredients", "location": "US"},
    {"industry": "Whey Ingredients", "industry_context": "Dairy Inputs", "location": "Northern Europe"},
    {"industry": "Molasses", "industry_context": "Sugar & Sweeteners", "location": "Oceania"},
]

company_name_examples = [
    "ExxonMobil",
    "Borouge",
    "Sigma Chemtrade",
    "HPCL Mittal Energy",
    "L M Goes Embalagens",
    "Westrock",
    "International Paper",
    "Dine Cartonnages",
    "Jiangin Yonghe Packaging Products",
    "Fritz Foss",
    "Husky Technologies",
    "KRC Custom Manufacturing",
    "Braroll Acessorios Industriais",
    "Jindal Films",
    "Klöckner Pentaplast",
    "Klockner Pentaplast",
    "Entertainment Partners",
    "Universal McCann",
    "Little Island Productions",
    "Commerzbank AG",
    "Linklaters",
    "CBS News",
    "Deloitte",
    "Bloomberg",
]
